# Generated by Django 2.1.5 on 2020-04-02 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kitup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_datetime', models.DateTimeField()),
                ('end_time', models.TimeField()),
                ('min_age', models.IntegerField(default=14)),
                ('max_age', models.IntegerField(default=70)),
                ('min_rating', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('post_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Match')),
            ],
            options={
                'verbose_name_plural': 'Match Participants',
            },
        ),
        migrations.CreateModel(
            name='MatchParticipantReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[(kitup.models.ReportReason('Offensive Language'), 'Offensive Language'), (kitup.models.ReportReason('Offensive Behaviour'), 'Offensive Behaviour'), (kitup.models.ReportReason('Racism'), 'Racism'), (kitup.models.ReportReason('No Show'), 'No Show'), (kitup.models.ReportReason('Unfair'), 'Unfair')], max_length=19)),
                ('desc', models.CharField(max_length=80)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Match')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL)),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Player Reports',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_images')),
                ('date_of_birth', models.DateField()),
                ('rating', models.FloatField(default=0)),
                ('reported', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_participants', models.IntegerField()),
                ('sport_picture', models.ImageField(upload_to='sport_images')),
            ],
            options={
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.MatchLocation'),
        ),
        migrations.AddField(
            model_name='match',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Sport'),
        ),
        migrations.AlterUniqueTogether(
            name='matchparticipant',
            unique_together={('profile', 'match')},
        ),
    ]
