# Generated by Django 3.0.4 on 2020-03-11 23:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(primary_key=True, serialize=False)),
                ('report_maker', models.IntegerField()),
                ('report_subject', models.IntegerField()),
                ('reason', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('team_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('picture', models.ImageField(upload_to='')),
                ('rating', models.IntegerField()),
                ('strikes', models.IntegerField()),
                ('joined_on', models.DateTimeField(default=datetime.datetime(2020, 3, 11, 23, 5, 26, 559706, tzinfo=utc))),
                ('last_login', models.DateTimeField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField()),
                ('min_rating', models.IntegerField()),
                ('team_home_score', models.IntegerField()),
                ('team_away_score', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Users')),
            ],
            options={
                'unique_together': {('player_id', 'game_id')},
            },
        ),
    ]
