# Generated by Django 3.0.4 on 2020-03-31 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kitup.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='MatchParticipantReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[(kitup.models.ReportReason['OFFENSIVE_LANGUAGE'], 'Offensive Language'), (kitup.models.ReportReason['OFFENSIVE_BEHAVIOUR'], 'Offensive Behaviour'), (kitup.models.ReportReason['RACISM'], 'Racism'), (kitup.models.ReportReason['NO_SHOW'], 'No Show'), (kitup.models.ReportReason['UNFAIR'], 'Unfair')], max_length=19)),
                ('desc', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Player Reports',
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporting_user',
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name_plural': 'Sports'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='strikes',
            new_name='reported',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='max_team_size',
            new_name='max_participants',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_away_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_home_score',
        ),
        migrations.AddField(
            model_name='match',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='max_age',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='match',
            name='min_age',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='matchparticipantreport',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Match'),
        ),
        migrations.AddField(
            model_name='matchparticipantreport',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchparticipantreport',
            name='reporting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Match'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitup.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='matchparticipant',
            unique_together={('profile', 'match')},
        ),
    ]
