# Generated by Django 3.0.4 on 2020-03-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitup', '0002_auto_20200331_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_owner',
            new_name='owner',
        ),
    ]
