# Generated by Django 3.0.4 on 2020-03-15 00:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kitup', '0003_auto_20200311_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 0, 45, 52, 303922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
