# Generated by Django 3.0.4 on 2020-03-16 00:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kitup', '0004_auto_20200315_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AddField(
            model_name='match',
            name='match_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitup.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitup.Sport'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 0, 12, 44, 969564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user_id', 'game_id')},
        ),
    ]
