# Generated by Django 3.0.4 on 2020-03-16 00:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kitup', '0005_auto_20200316_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sport_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitup.Sport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 0, 22, 19, 389174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
